### ISSUE TITLE
Agree on and implement URL naming

### ISSUE THREAD

**Issue by etoledom** [Automattic/Gravatar-SDK-iOS#134]
Let's agree on how to use the `URL` word in names of types and fields.

From what I've seen, this works:

Always uppercased, **except** when it's **at the beginning** of a field, variable, method name, or if **it's the word `url` alone**.
My question is at the middle of the name. I've usually tended to make them lowercased, but as a general rule, it's simpler if we make it also uppercased (one less exception).

### Some examples:

**Types: Always uppercased:**

- `URLSomething`, `SomeURLThing` , `SomethingURL`

**Fields, methods, methd labels, and local variables:**

- Prefixing with `url` lowercased:
  - `let urlSomething` 
  - `func urlThing() -> URL`
- Postfixing with `URL` Uppercased:
  - `let someURL`
  - `func somethingURL()`
- `url` alone lowercased:
  - `let url`
- `URL` in the middle uppercased:
  - `let someURLThing`
  - `func avatarURLThing() -> AvatarURL`

**Comment by andrewdmontgomery** [comment]
I like these examples.  I was on the fence about this.  I was thinking that camelCase was best, unless specifically referring to the `URL` type.

But the `URL` type is capitalized for a reason, too.  In formal writing, `URL` should be capitalized because it is an acronym.  Technically I guess it would be an Initialism, since an acronym needs to be a word, and I refuse to pronounce "Url" as a word.

But anyway, keeping it upppercase, except where it cannot be uppercased, makes a lot of sense to me now.

**Comment by pinarol** [comment]
Thanks for brining this up. Those examples look good to me!

**Comment by pinarol** [comment]
I guess we can apply those to method parameter names too.

if it is at the end, uppercased:

`func fetch(withURL: ) -> URL`

If it's alone lowercased:

`func fetch(_ url: ) -> URL`
