### ISSUE TITLE
Add new customURL options to `DefaultAvatarOption`

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#152]
1. Custom: A URL of user’s choice, in case they want to use their own fallback image. (Android already has [such option](https://github.com/Automattic/Gravatar-SDK-Android/blob/48c8659948683ddeef3c8147d53b6332d02843ac/gravatar/src/main/java/com/gravatar/DefaultAvatarOption.kt#L68), and our backend supports it, so we can)

~~2. Gravatar logo, it fallbacks to https://www.gravatar.com/avatar/00000000000000000000000000000000?s=200 (“s” parameter to be adjusted) This will be our default in the profile card component.~~

Update: I completely missed that the gravatar logo is already the default behavior when one doesn't set this parameter. Although I like the idea of making this an explicit option. Let's discuss if this is a good idea.

**Comment by etoledom** [comment]
swift enums don't support both raw values and associated values in a same enum type.

If we want to continue using an enum, we need an associated value for the `customURL` case, so all raw values will need to be manually written in a big switch case:

```swift
public enum DefaultAvatarOption {
    case status404
    case mysteryPerson
    case identicon
    case monsterId
    case wavatar
    case retro
    case roboHash
    case transparentPNG
    case customURL(URL)
}

extension DefaultAvatarOption {
    var rawValue: String {
        switch self {
        case .status404:
            "404"
        case .mysteryPerson:
            "mp"
        case .identicon:
            "identicon"
        case .monsterId:
            "monsterid"
        case .wavatar:
            "wavatar"
        case .retro:
            "retro"
        case .roboHash:
            "robohash"
        case .transparentPNG:
            "blank"
        case .customURL(let url):
            url.absoluteString
        }
    }
}
```

This is the way to keep it as an enum, though we don't really need an enum since switching on this type shouldn't be common.
I don't like the definition of case name and rawValue being separately.

---

Another option is to use a `struct`

```swift
public struct DefaultAvatarOption {
    let rawValue: String

    private init(_ optionLiteral: String) {
        self.rawValue = optionLiteral
    }
}

extension DefaultAvatarOption {
    public static let status404 = DefaultAvatarOption("404")
    public static let mysteryPerson = DefaultAvatarOption("mp")
    public static let identicon = DefaultAvatarOption("identicon")
    public static let monsterId = DefaultAvatarOption("monsterid")
    public static let wavatar = DefaultAvatarOption("wavatar")
    public static let retro = DefaultAvatarOption("retro")
    public static let roboHash = DefaultAvatarOption("robohash")
    public static let transparentPNG = DefaultAvatarOption("blank")
    public static func customURL(_ url: URL) -> DefaultAvatarOption {
        DefaultAvatarOption(url.absoluteString)
    }
}
```

In this case, the definition of the option goes together with it's literal value (as it was previously), so declaring new options is a one step process.
The init of the struct is private, so it's not possible to create new cases from outside of this definition.

Switching over DefaultAvatarOption will always need a `default:`, since the compiler won't be able to check for exhaustivity. But again, I don't think this is meant to be used in switches.

---

In both cases `allCases` has to be written manually, since it can't be synthesised automatically.
In both cases, the changes are compatible with the current usage of the public API. I've tried both options and there's no change required anywhere else in the SDK, tests, or demo app.

@pinarol  - Any preference?

**Comment by pinarol** [comment]
I am fine with both. I find the first one a bit easier to read & understand. But that's all.

```
public enum DefaultAvatarOption {
    case status404
    case mysteryPerson
    case identicon
    case monsterId
    case wavatar
    case retro
    case roboHash
    case transparentPNG
    case customURL(URL)
}
```
